"""FIFO lot tracking and adjusted cost basis, per docs/SPEC.md section 9.

Positions are never entered directly — everything here is derived by
replaying the `trades` table in chronological order. This module is pure
(no DB access) so it can be unit tested against plain trade dicts.

Trade dict shape (see src/db/models.py):
    security_id, trade_date, type, quantity, price, commission, currency

Stock-affecting types: STOCK_BUY (opens a FIFO lot), STOCK_SELL and
ASSIGNMENT (both close lots FIFO — an ASSIGNMENT is the call being
exercised, i.e. shares called away at the strike price).
Premium-affecting types: CALL_SELL_OPEN (premium received),
CALL_BUY_CLOSE (premium paid to close). EXPIRATION and DIVIDEND do not
touch stock lots or premium totals (a dividend is cash income, not part
of the options premium yield).
"""
from dataclasses import dataclass, field
from typing import Optional

STOCK_OPEN_TYPES = ("STOCK_BUY",)
STOCK_CLOSE_TYPES = ("STOCK_SELL", "ASSIGNMENT")
PREMIUM_RECEIVE_TYPES = ("CALL_SELL_OPEN",)
PREMIUM_PAY_TYPES = ("CALL_BUY_CLOSE",)


@dataclass
class OpenLot:
    trade_id: int
    open_date: str
    quantity: float          # shares remaining in this lot
    price: float              # per-share purchase price
    commission_per_share: float
    currency: str


@dataclass
class RealizedSale:
    open_trade_id: int
    close_trade_id: int
    open_date: str
    close_date: str
    quantity: float
    buy_price: float
    sell_price: float
    buy_commission_alloc: float
    sell_commission_alloc: float
    currency: str

    @property
    def gain(self) -> float:
        proceeds = self.quantity * self.sell_price - self.sell_commission_alloc
        cost = self.quantity * self.buy_price + self.buy_commission_alloc
        return proceeds - cost


@dataclass
class FifoResult:
    open_lots: list[OpenLot] = field(default_factory=list)
    realized_sales: list[RealizedSale] = field(default_factory=list)

    @property
    def shares_held(self) -> float:
        return sum(lot.quantity for lot in self.open_lots)

    @property
    def avg_cost_raw(self) -> Optional[float]:
        shares = self.shares_held
        if shares <= 0:
            return None
        total_cost = sum(lot.quantity * (lot.price + lot.commission_per_share) for lot in self.open_lots)
        return total_cost / shares


def compute_fifo(trades: list[dict]) -> FifoResult:
    """Replays STOCK_BUY / STOCK_SELL / ASSIGNMENT for one security in
    trade_date order and returns the remaining open lots plus the
    realized sales generated by closes, oldest lot first (FIFO).
    """
    ordered = sorted(trades, key=lambda t: (t["trade_date"], t.get("id") or 0))
    lots: list[OpenLot] = []
    sales: list[RealizedSale] = []

    for t in ordered:
        if t["type"] in STOCK_OPEN_TYPES:
            qty = t["quantity"]
            commission_per_share = (t["commission"] / qty) if qty else 0.0
            lots.append(OpenLot(
                trade_id=t["id"],
                open_date=t["trade_date"],
                quantity=qty,
                price=t["price"],
                commission_per_share=commission_per_share,
                currency=t["currency"],
            ))
        elif t["type"] in STOCK_CLOSE_TYPES:
            remaining_to_close = t["quantity"]
            close_commission_per_share = (t["commission"] / t["quantity"]) if t["quantity"] else 0.0
            while remaining_to_close > 1e-9:
                if not lots:
                    raise ValueError(
                        f"FIFO underflow: trying to close {remaining_to_close} shares "
                        f"with no open lots (trade {t.get('id')})"
                    )
                lot = lots[0]
                qty_from_lot = min(lot.quantity, remaining_to_close)
                sales.append(RealizedSale(
                    open_trade_id=lot.trade_id,
                    close_trade_id=t["id"],
                    open_date=lot.open_date,
                    close_date=t["trade_date"],
                    quantity=qty_from_lot,
                    buy_price=lot.price,
                    sell_price=t["price"],
                    buy_commission_alloc=qty_from_lot * lot.commission_per_share,
                    sell_commission_alloc=qty_from_lot * close_commission_per_share,
                    currency=t["currency"],
                ))
                lot.quantity -= qty_from_lot
                remaining_to_close -= qty_from_lot
                if lot.quantity <= 1e-9:
                    lots.pop(0)

    return FifoResult(open_lots=lots, realized_sales=sales)


def net_premium_collected(trades: list[dict]) -> float:
    """Net option premium for one security: money received opening calls
    minus money paid closing them. Contract size is fixed at 100 shares.
    """
    total = 0.0
    for t in trades:
        if t["type"] in PREMIUM_RECEIVE_TYPES:
            total += t["quantity"] * t["price"] * 100 - t["commission"]
        elif t["type"] in PREMIUM_PAY_TYPES:
            total -= t["quantity"] * t["price"] * 100 + t["commission"]
    return total


def adjusted_cost_basis(fifo_result: FifoResult, total_premium: float) -> Optional[float]:
    """בסיס עלות מתואם: עלות המניות (raw) פחות סך הפרמיות נטו, לפי מניה."""
    shares = fifo_result.shares_held
    raw = fifo_result.avg_cost_raw
    if shares <= 0 or raw is None:
        return None
    return raw - (total_premium / shares)
